##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- name: Install Inxi when CentOS
  yum:
    name: inxi
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Inxi when Ubuntu
  apt:
    name: inxi
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Run inxi
  shell: inxi -b -c0 -n > inxi.log
  args:
    chdir: '{{ dest_path }}/'
