
#git
- name: set git proxy(http)
  shell: "git config --global http.proxy {{ http_proxy }}"
  when: http_proxy is defined
  ignore_errors: yes 

- name: set git proxy(https) 
  shell: "git config --global https.proxy {{https_proxy}}"
  when: https_proxy is defined 
  ignore_errors: yes

