##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---
# Execute compute benchmark plan and collect data
# - system information
# - test condition
# - performance metrics

- hosts: compute

  pre_tasks:

  - name: check ssh connection
    ping:

  - name: create result directory
    file:
      path: "{{ qtip_results }}/{{ inventory_hostname }}"
      state: directory
    delegate_to: localhost

  roles:
  - development-tools

  tags: [setup]


- hosts: compute

  roles:

    - { role: inxi, tags: [inxi, sysinfo] }
    - { role: unixbench, tags: [unixbench, float, int] }
    - { role: openssl, tags: [openssl, ssl]}
    - { role: nDPI, tags: [ndpi, dpi]}
    - { role: ramspeed, tags: [ramspeed, mem]}

  post_tasks:
  - name: calculate QPI of compute
    calculate:
      metrics:
        ssl_rsa: "{{ ssl_rsa_metrics }}"
      spec:   "{{ qtip_resources }}/QPI/compute.yaml"
    register: qpi_result
    delegate_to: localhost
    tags: [qpi]


- hosts: localhost

  pre_tasks:

  - name: aggregate QPI results from all tested nodes
    aggregate:
      group: compute
    register: pod_result
    tags: [pod]

  # Generate and publish report

  roles:
    - role: opnfv-testapi
      action: report
      when: testapi_url is defined
