##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---

- name: aggregate results from all tested nodes
  aggregate:
    group: compute
  register: pod_result

- name: dump pod results
  copy:
    content: "{{ pod_result }}"
    dest: "{{ qtip_pod_results }}/qtip-report.json"
