##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
    - name: Get current timestamp
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"

    - name: Make some directories needed
      file:
        path: '{{ ansible_env.HOME }}/qtip_result/{{ timestamp }}/{{ ansible_hostname }}'
        state: directory

    - include: ../inxi.yaml
      vars:
        dest_path: '{{ ansible_env.HOME }}/qtip_result/{{ timestamp }}/{{ ansible_hostname }}/'

    - include: ../top.yaml
      vars:
        dest_path: '{{ ansible_env.HOME }}/qtip_result/{{ timestamp }}/{{ ansible_hostname }}/'

    - name: Benchmarking IntMem Bandwidth and FloatMem Bandwidth
      shell: '{{ item }}'
      with_items:
        - ~/ramspeed/ramsmp-3.5.0/ramsmp -b 3 -l 5 -p 1 >> Intmem
        - ~/ramspeed/ramsmp-3.5.0/ramsmp -b 6 -l 5 -p 1 >> Floatmem
      args:
        chdir: '{{ ansible_env.HOME }}/qtip_result/{{ timestamp }}/{{ ansible_hostname }}/'

    - name: Fetch result files to local manchine
      synchronize:
        mode: pull
        src: '{{ ansible_env.HOME }}/qtip_result/'
        dest: '{{ result_dir }}/ramspeed/logs/'
