##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Making ramspeed directory
      file:
        path: '{{ result_dir }}/ramspeed/logs/'
        state: directory

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
      - name: Cleaning ramspeed directory
        file:
          path: '{{ ansible_env.HOME }}/ramspeed'
          state: absent

      - name: Cleaning qtip_result directory
        file:
          path: '{{ ansible_env.HOME }}/qtip_result'
          state: absent

      - include: ../prepare_env.yaml

      - name: Installing RAM_Speed dependencies if CentOS
        yum:
          name: '{{ item }}'
          state: present
        when: ansible_os_family == "RedHat"
        with_items:
          - gcc
          - wget

      - name: Installing RAM_Speed dependencies if Ubuntu
        apt:
          name: '{{ item }}'
          state: present
        when: ansible_os_family == "Debian"
        with_items:
          - gcc
          - wget

      - name: Making ramspeed temporary directory
        file:
          path: '{{ ansible_env.HOME }}/ramspeed'
          state: directory

      - name: Fetch and untar ramspeed.tar.gz
        unarchive:
          # TODO: Need to upload this file to http://artifacts.opnfv.org/qtip/utilities
          src: https://docs.google.com/uc?id=0B92Bp5LZTM7gRFctalZLMktTNDQ
          dest: '{{ ansible_env.HOME }}/ramspeed/'
          remote_src: True

      - name: Build ramsmp
        shell: ./build.sh
        args:
          chdir: '{{ ansible_env.HOME }}/ramspeed/ramsmp-3.5.0'
