##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
# zhihui.wu1@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    dhrystone: '{{ dhrystone }}'
    whetstone: '{{ whetstone }}'

  tasks:
    - name: Making dhrystone directory
      file:
        path: '{{ result_dir }}/dhrystone/logs/'
        state: directory
      when: dhrystone

    - name: Making whetstone directory
      file:
        path: '{{ result_dir }}/whetstone/logs/'
        state: directory
      when: whetstone

- hosts: hosts
  become: yes
  remote_user: root

  tasks:
    - name: Cleaning tempT directory
      file:
        path: '{{ ansible_env.HOME }}/tempT'
        state: absent

    - name: Cleaning qtip_result directory
      file:
        path: '{{ ansible_env.HOME }}/qtip_result'
        state: absent

    - include: ../prepare_env.yaml

    - name: Installing UnixBench dependencies if CentOS
      yum:
        name: '{{ item }}'
        state: present
      when: ansible_os_family == "RedHat"
      with_items:
        - git
        - gcc
        - patch
        - perl-Time-HiRes

    - name: Installing UnixBench dependencies if Ubuntu
      apt:
        name: '{{ item }}'
        state: present
      when: ansible_os_family == "Debian"
      with_items:
        - git
        - gcc
        - patch
        - perl

    - name: Clone UnixBench
      git:
        repo: https://github.com/kdlucas/byte-unixbench.git
        dest: '{{ ansible_env.HOME }}/tempT/'

    - name: Make UnixBench
      shell: make --directory $HOME/tempT/UnixBench/
